-- Pitstop Solutions core commerce schema.
-- Run admin-auth-migration.sql first, then run this file in the Supabase SQL editor.

create extension if not exists "pgcrypto";

create type public.order_status as enum (
  'pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded'
);
create type public.payment_status as enum (
  'pending', 'authorized', 'paid', 'failed', 'refunded'
);
create type public.address_type as enum ('shipping', 'billing');

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  image_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  external_id text unique,
  category_id bigint not null references public.categories(id) on delete restrict,
  name text not null,
  slug text not null unique,
  sku text not null unique,
  short_description text,
  full_description text,
  price numeric(12, 2) not null check (price >= 0),
  original_price numeric(12, 2) check (original_price is null or original_price >= price),
  badge text,
  specifications jsonb not null default '{}'::jsonb,
  features jsonb not null default '[]'::jsonb,
  compatible_with text,
  options jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.inventory (
  product_id bigint primary key references public.products(id) on delete cascade,
  stock_count integer not null default 0 check (stock_count >= 0),
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  updated_at timestamptz not null default now()
);

create table public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity_change integer not null check (quantity_change <> 0),
  reason text not null,
  reference_id uuid,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  address_type public.address_type not null default 'shipping',
  label text,
  recipient_name text not null,
  line1 text not null,
  line2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  country text not null default 'India',
  phone text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  session_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cart_owner_check check (user_id is not null or session_id is not null)
);

create table public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id uuid not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  selected_options jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cart_id, product_id, selected_options)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('PS-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))),
  user_id uuid references public.profiles(id) on delete set null,
  customer_name text,
  customer_email text,
  customer_phone text,
  status public.order_status not null default 'pending',
  payment_status public.payment_status not null default 'pending',
  shipping_address jsonb not null,
  billing_address jsonb,
  subtotal numeric(12, 2) not null default 0 check (subtotal >= 0),
  shipping_amount numeric(12, 2) not null default 0 check (shipping_amount >= 0),
  tax_amount numeric(12, 2) not null default 0 check (tax_amount >= 0),
  total_amount numeric(12, 2) not null default 0 check (total_amount >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  sku text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  selected_options jsonb not null default '{}'::jsonb,
  line_total numeric(12, 2) generated always as (unit_price * quantity) stored
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  provider text not null,
  provider_payment_id text,
  amount numeric(12, 2) not null check (amount >= 0),
  currency char(3) not null default 'INR',
  status public.payment_status not null default 'pending',
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete restrict,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index products_category_id_idx on public.products(category_id);
create index products_active_idx on public.products(is_active);
create index product_images_product_id_idx on public.product_images(product_id);
create index inventory_movements_product_id_idx on public.inventory_movements(product_id);
create index addresses_user_id_idx on public.addresses(user_id);
create index carts_user_id_idx on public.carts(user_id);
create index cart_items_cart_id_idx on public.cart_items(cart_id);
create index orders_user_id_idx on public.orders(user_id);
create index order_items_order_id_idx on public.order_items(order_id);
create index admin_audit_logs_admin_created_idx on public.admin_audit_logs(admin_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger categories_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger inventory_updated_at before update on public.inventory for each row execute function public.set_updated_at();
create trigger addresses_updated_at before update on public.addresses for each row execute function public.set_updated_at();
create trigger carts_updated_at before update on public.carts for each row execute function public.set_updated_at();
create trigger cart_items_updated_at before update on public.cart_items for each row execute function public.set_updated_at();
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();
create trigger payments_updated_at before update on public.payments for each row execute function public.set_updated_at();

create or replace view public.storefront_products
with (security_invoker = true)
as
select
  coalesce(p.external_id, p.slug) as id,
  p.name,
  c.name as category,
  p.price,
  p.original_price as "originalPrice",
  p.badge,
  p.sku,
  coalesce(i.stock_count, 0) > 0 as "inStock",
  coalesce(i.stock_count, 0) as "stockCount",
  p.short_description as "shortDesc",
  p.full_description as "fullDesc",
  p.specifications as specs,
  p.features,
  p.compatible_with as compatible,
  p.options,
  coalesce(image_list.images, array[]::text[]) as images
from public.products p
join public.categories c on c.id = p.category_id
left join public.inventory i on i.product_id = p.id
left join lateral (
  select array_agg(pi.image_url order by pi.sort_order, pi.id) as images
  from public.product_images pi
  where pi.product_id = p.id
) image_list on true
where p.is_active = true and c.is_active = true;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.inventory enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.addresses enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.admin_audit_logs enable row level security;

create policy "Admins manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage product images" on public.product_images for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage inventory" on public.inventory for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage inventory movements" on public.inventory_movements for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage payments" on public.payments for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins view audit logs" on public.admin_audit_logs for select using (public.is_admin());
create policy "Admins create audit logs" on public.admin_audit_logs for insert with check (public.is_admin() and admin_id = auth.uid());

create policy "Public can view active categories" on public.categories for select using (is_active = true);
create policy "Public can view active products" on public.products for select using (is_active = true);
create policy "Public can view product images" on public.product_images for select using (exists (
  select 1 from public.products p where p.id = product_id and p.is_active = true
));
create policy "Public can view active product inventory" on public.inventory for select using (exists (
  select 1 from public.products p where p.id = inventory.product_id and p.is_active = true
));

create policy "Users manage their addresses" on public.addresses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their carts" on public.carts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their cart items" on public.cart_items for all using (exists (
  select 1 from public.carts c where c.id = cart_id and c.user_id = auth.uid()
)) with check (exists (
  select 1 from public.carts c where c.id = cart_id and c.user_id = auth.uid()
));
create policy "Users can create their orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Users view their orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users view their order items" on public.order_items for select using (exists (
  select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()
));
create policy "Users view their payments" on public.payments for select using (exists (
  select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()
));

insert into public.categories (name, slug, description, sort_order)
values
  ('IC Powertrain', 'ic-powertrain', 'Engines, transmissions, drivetrain and fuel system components.', 1),
  ('Chassis & Suspension', 'chassis-suspension', 'Chassis, steering and suspension components.', 2),
  ('Braking System', 'braking-system', 'Brake hydraulics, rotors, calipers and pedals.', 3),
  ('Wheels & Controls', 'wheels-controls', 'Wheels, tyres, hubs and driver controls.', 4)
on conflict (slug) do update set description = excluded.description, sort_order = excluded.sort_order;
